[build]
  command = "npm run build"
  publish = "dist"

[build.environment]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# CORS headers per evitare problemi cross-origin
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET,HEAD,OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"